function(renderer_setup)
    if(NOT EXISTS ${CMAKE_BINARY_DIR}/assets/)
        file(MAKE_DIRECTORY ${CMAKE_BINARY_DIR}/assets/)
    endif()
    if(NOT EXISTS ${CMAKE_BINARY_DIR}/assets/cache)
        file(MAKE_DIRECTORY ${CMAKE_BINARY_DIR}/assets/cache)
    endif()

    if(CMAKE_GENERATOR MATCHES "Visual Studio")
        set_target_properties(renderer PROPERTIES VS_DEBUGGER_WORKING_DIRECTORY "${CMAKE_BINARY_DIR}/$<CONFIG>")
    endif()
endfunction()

function(renderer_symlink_binary SRC_DIR DST_DIR)
    if(NOT UNIX)
        file(TO_NATIVE_PATH ${CMAKE_BINARY_DIR}/${DST_DIR} DST_PATH)
        file(TO_NATIVE_PATH ${CMAKE_CURRENT_FUNCTION_LIST_DIR}/${SRC_DIR} SRC_PATH)
        if(NOT EXISTS ${DST_PATH})
            message(STATUS "Creating symlink/junction between ${DST_PATH} and ${SRC_PATH}")
            execute_process(COMMAND cmd.exe /c mklink /D /J "${DST_PATH}" "${SRC_PATH}" >NUL)
        endif()
    else()
        message(WARNING "Symlink for unix not implemented.")
    endif()
endfunction()

function(renderer_symlink_assets)
    renderer_symlink_binary(/src/shared/shared /assets/shared/)
    renderer_symlink_binary(/assets/shaders/ /assets/shaders/)
    renderer_symlink_binary(/assets/pipelines /assets/pipelines/)
    renderer_symlink_binary(/assets/fonts /assets/fonts/)
endfunction()
