#ifndef REN_SHARED_RESOURCES
#define REN_SHARED_RESOURCES

#include "shared/shared_types.h"

#if __cplusplus
// Host side treats indices as pairs.
static SHADER_CONSTEXPR uint REN_SHADER_RESOURCE_INDEX_DIFF = 1;
#else
// Shader side treats indices as absolutes.
static SHADER_CONSTEXPR uint REN_SHADER_RESOURCE_INDEX_DIFF = 2;
#endif
static SHADER_CONSTEXPR uint REN_SHADER_INVALID_INDEX = 500000 * REN_SHADER_RESOURCE_INDEX_DIFF;
static SHADER_CONSTEXPR uint REN_GLOBAL_INDEX_BUFFER = REN_SHADER_INVALID_INDEX - REN_SHADER_RESOURCE_INDEX_DIFF;
static SHADER_CONSTEXPR uint REN_GLOBAL_INSTANCE_TRANSFORM_BUFFER = REN_GLOBAL_INDEX_BUFFER - REN_SHADER_RESOURCE_INDEX_DIFF;
static SHADER_CONSTEXPR uint REN_GLOBAL_MATERIAL_INSTANCE_BUFFER = REN_GLOBAL_INSTANCE_TRANSFORM_BUFFER - REN_SHADER_RESOURCE_INDEX_DIFF;
static SHADER_CONSTEXPR uint REN_GLOBAL_INSTANCE_INDICES_BUFFER = REN_GLOBAL_MATERIAL_INSTANCE_BUFFER - REN_SHADER_RESOURCE_INDEX_DIFF;
static SHADER_CONSTEXPR uint REN_GLOBAL_SCENE_INFORMATION_BUFFER = REN_GLOBAL_INSTANCE_INDICES_BUFFER - REN_SHADER_RESOURCE_INDEX_DIFF;
static SHADER_CONSTEXPR uint REN_GLOBAL_LIGHT_LIST_BUFFER = REN_GLOBAL_SCENE_INFORMATION_BUFFER - REN_SHADER_RESOURCE_INDEX_DIFF;

#endif
